[package]
name = "cwpack-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.cwpack-rs]
path = ".."

[[bin]]
name = "roundtrip_vs_ffi"
path = "fuzz_targets/roundtrip_vs_ffi.rs"
test = false
doc = false
